In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Introduction to Tensors
### Creating tensors
Pytorch tensors are creating using [`torch.tensor()`](https://docs.pytorch.org/docs/stable/tensors.html)

In [2]:
# Scalers
scaler = torch.tensor(18)
print(scaler)
print(scaler.ndim)

tensor(18)
0


In [3]:
# Get tensor back to python int
scaler.item()

18

In [4]:
# Vector
vector = torch.tensor([1,8,0,9,1,9])
print(vector)
print("dim: ", vector.ndim)
print("shape: ", vector.shape)

tensor([1, 8, 0, 9, 1, 9])
dim:  1
shape:  torch.Size([6])


In [13]:
# Matrix 
MATRIX = torch.tensor([[1,8,0],
                       [0,9,1],
                       [1,9,1]])

print(MATRIX)
print("dim:", MATRIX.ndim)
print("shape:", MATRIX.shape)

tensor([[1, 8, 0],
        [0, 9, 1],
        [1, 9, 1]])
dim: 2
shape: torch.Size([3, 3])


In [14]:
# Tensor
TENSOR = torch.tensor([[[0,1,1,5],[1,3,2,6],[9,4,-5,-3]],[[1,2,2,6],[3,5,4,8],[-1,0,-2,7]]])
print(TENSOR)
print("dim:", TENSOR.ndim)
print("shape:", TENSOR.shape)

tensor([[[ 0,  1,  1,  5],
         [ 1,  3,  2,  6],
         [ 9,  4, -5, -3]],

        [[ 1,  2,  2,  6],
         [ 3,  5,  4,  8],
         [-1,  0, -2,  7]]])
dim: 3
shape: torch.Size([2, 3, 4])


### Random Tensors
**Why random tensors?** 

Random tensors are important because the way neural networks learn is that they started with tensors full with random numbers and then adjust those random numbers to better represent the data.

`started with random numbers -> look at the data -> update random numbers`

In [19]:
# Create a random tensor
random_tensor = torch.rand(2,3,4)
print(random_tensor)
print("dim:", random_tensor.ndim)
print("shape:", random_tensor.shape)


tensor([[[0.6897, 0.9165, 0.5762, 0.6047],
         [0.2757, 0.9595, 0.3442, 0.3913],
         [0.1584, 0.7062, 0.3428, 0.3941]],

        [[0.1924, 0.8375, 0.9932, 0.9279],
         [0.2147, 0.8458, 0.5179, 0.4256],
         [0.5079, 0.9256, 0.3264, 0.0441]]])
dim: 3
shape: torch.Size([2, 3, 4])


In [21]:
# Creating random tensor similar to an image tensor
random_image_tensor = torch.rand(size=(3, 224, 224))
print("dim:", random_image_tensor.ndim)
print("shape:", random_image_tensor.shape)

dim: 3
shape: torch.Size([3, 224, 224])


### Zeros and Ones

In [29]:
# Creating tensor full of Zeros
zeros = torch.zeros(size=(2,4))
print(zeros)
print("dim:", zeros.ndim)
print("shape:", zeros.shape)

zeros = torch.zeros(size=(2,3,4))
print("\n",zeros)
print("dim:", zeros.ndim)
print("shape:", zeros.shape)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.]])
dim: 2
shape: torch.Size([2, 4])

 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
dim: 3
shape: torch.Size([2, 3, 4])


In [30]:
# Creating tensor full of Ones
ones = torch.ones(size=(2,3))
print(ones)
print("dim:", ones.ndim)
print("shape:", ones.shape)

ones = torch.ones(size=(1,2,3))
print("\n",ones)
print("dim:", ones.ndim)
print("shape:", ones.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
dim: 2
shape: torch.Size([2, 3])

 tensor([[[1., 1., 1.],
         [1., 1., 1.]]])
dim: 3
shape: torch.Size([1, 2, 3])


### Creating  range tensors and tensors-like

In [33]:
# Use torch.arange -> torch.range is deprecated and will be removed in a future
tensor_range = torch.arange(start=1, end=11, step=1)
tensor_range

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
# Creating tensor like -> it make tensor of n-dim, is equal to dim of input tensor
tensor_like = torch.ones_like(input=tensor_range)
tensor_like

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### Tensor datatypes
**Note:** Tensor datatype is one of the 3 big errors you'll run into with Pytorch & Deep Learning:
1. Tensors are not datatypes
2. Tensors are not right shape
3. Tensors are not on right device

In [42]:
# Float 32 Tensors
float32_tensor = torch.tensor(
    [1,8,0,9,1,9],
    dtype=None,           # What datatype is tensor (eg. float32, float16)
    device=None,          # What device is your tensor on
    requires_grad=False,   # Whether or not to track gradient with this tensor operation
)

float32_tensor

tensor([1, 8, 0, 9, 1, 9])

In [44]:
# Float 16 tensor
float16_tensor = torch.tensor([1,2,3,4], dtype=torch.float16)
print(float16_tensor)

float16_tensor = float32_tensor.type(torch.float16)
print(float16_tensor)

tensor([1., 2., 3., 4.], dtype=torch.float16)
tensor([1., 8., 0., 9., 1., 9.], dtype=torch.float16)


### Getting information from tensors (tensors attributes)

1. Tensors are not datatypes - to get datatype from tensor, can use `tensor.dtype`
2. Tensors are not right shape - to get shape from tensor, can use `tensor.shape`
3. Tensors are not on right device - to get device from tensor, can use `tensor.device`

In [45]:
# For some(any) tensor
some_tensor = torch.tensor([[1,2,3],[2,3,4]])

# Find out tensor details
print("Datatypes of tensor:", some_tensor.dtype)
print("Shape of tensor:", some_tensor.shape) # can we use tensor.size(), both give same result
print("Tensor on Device:", some_tensor.device)

Datatypes of tensor: torch.int64
Shape of tensor: torch.Size([2, 3])
Tensor on Device: cpu


### Manipulating Tensor
Tensors Operation Include:
- Addition
- Subraction
- Multiplication (Elementwise)
- Division
- Matrix Multiplication

In [ ]:
# Addition
tensorX = torch.tensor([2,4,6,8])
tensorY = torch.tensor([3,5,7,9])

tensorA = torch.tensor([1,8,0,9])

# Addition by Scaler
print(tensorA + 10)

# Addition by another tensor
print(tensorX+tensorY)

tensor([11, 18, 10, 19])
tensor([ 5,  9, 13, 17])


In [48]:
# Subtration
tensorS = torch.tensor([9,0,8,1])

# Subtraction by Scaler
print(tensorS-5)

# Subtraction by another tensor
print(tensorX-tensorY)

tensor([ 4, -5,  3, -4])
tensor([-1, -1, -1, -1])


In [50]:
# Multiplication
tensorM = torch.tensor([0,1,1,5])
tensorY = torch.tensor([3,5,7,9])

# Multiplication by Scaler
print(tensorM*7)

# Multiplication by another tensor
print(tensorM*tensorY)

tensor([ 0,  7,  7, 35])
tensor([ 0,  5,  7, 45])


#### Try Pythorch in-built functions

In [51]:
# Addition
Add = torch.add(tensorX, tensorY)
Add

tensor([ 5,  9, 13, 17])

In [53]:
# Subtraction
Sub = torch.sub(tensorY, tensorS)
Sub

tensor([-6,  5, -1,  8])

In [52]:
# Multiplication
Mul = torch.mul(tensorX, tensorM)
Mul

tensor([ 0,  4,  6, 40])